### ISSUE TITLE
print function appends 1 as a suffix

### ISSUE THREAD

**Issue by vickeykumar** [mklement0/perli#5]
print function appends 1 as a suffix:

perli> print "Hello, world!";
Hello, world!1

**Comment by mklement0** [comment]
A core feature of perli is that you never need `print` to print the results of expressions; just use `"Hello, world!";` or `1 + 2` directly.

The extra `1` comes from evaluating the `print` call _itself_ as an expression, which returns `1`.

Because `print` without an explicit `\n` in the string argument doesn't print a newline right after, that `1` is directly appended to the output.

You can see that the `1` is a separate output more clearly if you use `say 'hi'`, for instance.

Hope that helps.
